name: ndnet
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pandas=2.2.3
  - numpy=2.2.6
  - plotly=6.1.2
  - pre-commit=4.2.0
  - matplotlib=3.10.0
  - mlflow=3.1.1
  - scikit-image=0.25.2
  - pip
  # Albumentations for image augmentation
  - albumentations=2.0.7
  - opencv=4.10.0
  - lightning=2.5.1
  - types-PyYAML=6.0.12.20250809
  # FastAPI and Uvicorn are included for web API setup
  - fastapi=0.116.0
  - uvicorn=0.35.0
  - pydantic=2.11.7
  - python-multipart=0.0.20
  - pip:
    - pytest==8.3.5
    - pytest-cov==6.2.0
    - torch==2.6.0+cu118
    - torchvision==0.21.0+cu118
    - --extra-index-url https://download.pytorch.org/whl/cu118
    - diffusers[torch]==0.34.0
    - transformers==4.55.3
    - accelerate==0.32.0
    - safetensors==0.5.3
    - peft==0.17.0
