dataset:
  dataset_path: ./data/processed/
  batch_size: 32
model:
  name_pretrained_model: resnet34
  saving_dir_experiments: ./checkpoints/resnet34/
  saving_dir_model: models
  num_classes: 7
  num_epoch: 15
  learning_rate: 0.001
  scheduler_step_size: 10
  scheduler_gamma: 0.1
  freeze_layers: true
  epoch_start_unfreeze: 10
  #layer_start_unfreeze: 0
  n_nodes: 256
  dropout: 0.3
  do_train: true
  do_test: true
data:
  do_resize: true
  size: 224
